from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
ASSET_ROOT = PROJECT_ROOT / "assets" / "monkey"
SETTINGS_PATH = PROJECT_ROOT / "settings.json"

DEFAULT_STATE = "idle"

SOURCE_SPRITE_SIZE = (64, 64)
SPRITE_SCALE = 2
DISPLAY_SPRITE_SIZE = (
    SOURCE_SPRITE_SIZE[0] * SPRITE_SCALE,
    SOURCE_SPRITE_SIZE[1] * SPRITE_SCALE,
)

FRAME_INTERVAL_MS = 140
BEHAVIOR_INTERVAL_MS = 33

WALK_SPEED_PX = 2.4
RUN_DISTANCE_PX = 260.0
RUN_SPEED_MULTIPLIER = 2.0
CURSOR_STOP_DISTANCE_PX = 28.0
CURSOR_FOLLOW_DISTANCE_PX = 420.0
CURSOR_ATTENTION_DISTANCE_PX = 150.0
DRAG_START_DISTANCE_PX = 5

SLEEP_AFTER_MS = 30_000
BLINK_MIN_DELAY_MS = 4_000
BLINK_MAX_DELAY_MS = 12_000
IDLE_VARIATION_MIN_DELAY_MS = 7_000
IDLE_VARIATION_MAX_DELAY_MS = 18_000

ANGRY_BUMP_DURATION_MS = 320
FALL_DURATION_MS = 520
LAND_DURATION_MS = 520
EAT_DURATION_MS = 850
HAPPY_DURATION_MS = 1_300
BLINK_DURATION_MS = 420
LOOK_AROUND_DURATION_MS = 900
SIT_DURATION_MS = 1_400
YAWN_DURATION_MS = 900
WAKE_DURATION_MS = 900

KNOCKBACK_DISTANCE_PX = 46.0
KNOCKBACK_HOP_HEIGHT_PX = 28.0
KNOCKBACK_FRAMES = 16

STARTING_CORNER = "bottom_right"
START_MARGIN_PX = 80
MOVEMENT_PAUSED = False

# --- v0.4 local, project-relative data (NEVER written outside the project) ---
DATA_DIR = PROJECT_ROOT / "data"
LOGS_DIR = PROJECT_ROOT / "logs"
SAVE_PATH = DATA_DIR / "save.json"
USER_SETTINGS_PATH = DATA_DIR / "settings.json"
LEGACY_SETTINGS_PATH = SETTINGS_PATH  # original ./settings.json is still honored
LOG_PATH = LOGS_DIR / "chaos_pet.log"
VOICE_LINES_PATH = DATA_DIR / "voice_lines.json"
SOUNDS_DIR = DATA_DIR / "sounds"
DIARY_PATH = DATA_DIR / "diary.json"

SAVE_SCHEMA_VERSION = 1
SETTINGS_SCHEMA_VERSION = 2
DIARY_SCHEMA_VERSION = 1
AUTOSAVE_INTERVAL_MS = 30_000
DIARY_HISTORY_DAYS = 90

# Defaults for the expanded settings.
DEFAULT_PET_NAME = "Bongo"
DEFAULT_PERSONALITY_ID = "playful"
SPEECH_ENABLED = True
DEBUG_ENABLED = False
SOUND_ENABLED = False
MOVEMENT_SPEED_MULTIPLIER = 1.0
ANIMATION_SPEED_MULTIPLIER = 1.0

# "Toggle Size" cycles the sprite scale through these values.
SCALE_CYCLE = (2, 3, 4)

# Rapid left-click escalation (combo within CLICK_COMBO_WINDOW_MS resets on a gap).
CLICK_COMBO_WINDOW_MS = 700
CLICK_ANGRY_COUNT = 3
CLICK_JUMP_COUNT = 5
JUMP_DURATION_MS = 600

# Speech bubble timing.
SPEECH_BUBBLE_MS = 2_600

# How long a stat tick represents (the behavior timer drives stat decay).
STATS_TICK_MS = 1_000

# Stat drift rate defaults.
HUNGER_DRIFT_RATE = 0.0005
ENERGY_DRIFT_RATE = 0.001
ANNOYANCE_DECAY_RATE = 4.0

# Local pseudo-random choices use a fixed seed so behavior remains replayable.
DETERMINISTIC_RNG_SEED = 1337
